### ISSUE TITLE
0.3.1-DB-Schema

### ISSUE THREAD

**Issue by cyrillbolliger** [bfh-l2p/ch.bfh.bti7081.s2018.green#22]

**Comment by cyrillbolliger** [comment]
@tscheckow hier wäre sonst noch das Diagram: https://drive.google.com/file/d/1eU6_mtSdNP56XJPTXb7zmwclqz-NRkxx/view?usp=sharing

**Comment by tscheckow** [comment]
@cyrillbolliger merci, sieht gut aus. wollen wir das morgen kurz besprechen, damit ich deine überlegungen verstehe und ggf. noch meine einbringen könnte?
