### ISSUE TITLE
8.1 Create a method for simple data access

### ISSUE THREAD

**Issue by cyrillbolliger** [bfh-l2p/ch.bfh.bti7081.s2018.green#30]
Sprint-Backlog ID: 8.1
Create a method for simple data access in the `DataContainer.java`class, so you don't have to get a new entitiy manager every time you need to access the database

**Comment by raaph** [comment]
I haven't started with that and won't be able to do it this weekend.

**Comment by raaph** [comment]
Sorry didnt' want to close it.

**Comment by lbischof** [comment]
Fixed by #36
