### ISSUE TITLE
Improve Managers and Tests

### ISSUE THREAD

**Issue by cyrillbolliger** [bfh-l2p/ch.bfh.bti7081.s2018.green#37]
Sprint-Backlog ID: 8.3 -> Moved to next sprint

- Refactor managers to reduce code duplication
- Add error handling for transactions
- Refactor tests: 1 test per method

**Comment by tscheckow** [comment]
Already addressed:
- refactoring of manager classes
- refactoring of test classes

To do:
- Add error handling for transactions
