### ISSUE TITLE
Review Task Core Data Model & Persistance

### ISSUE THREAD

**Issue by chraebeli** [bfh-l2p/ch.bfh.bti7081.s2018.green#51]
Please review diagramm and give a feedback to finish open task.

Link: https://drive.google.com/open?id=1Hf72DxeWTV5quuRnpx6LH88SiOk1DUMC

Thanks in advance!

**Comment by lbischof** [comment]
As far as I know the arrowheads for extends (Patient -> Person) should be closed and *unfilled*

**Comment by chraebeli** [comment]
redone in diagram.

**Comment by lbischof** [comment]
Merged in #53
