### ISSUE TITLE
Add exception handling

### ISSUE THREAD

**Issue by lbischof** [bfh-l2p/ch.bfh.bti7081.s2018.green#84]
https://github.com/bfh-l2p/ch.bfh.bti7081.s2018.green/blob/9865f1df2fdec9a204c0e2fcf3f0fc59d34f2601/src/main/java/ch/bfh/bti7081/s2018/green/presenters/AddEventPresenter.java#L36

**Comment by chraebeli** [comment]
issue is solved in new version
